'use client';

import { useState, memo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Calendar, Clock, AlertCircle, Share2, Info } from 'lucide-react';
import { cn } from '@/lib/utils/utils';

interface Deadline {
  type: string;
  display: string;
  urgency: 'critical' | 'soon' | 'comfortable' | 'passed';
}

interface DeadlineWidgetProps {
  locationName?: string;
  deadlines: Deadline[];
  nextDeadline?: Deadline | null;
}

const DeadlineWidget = memo(function DeadlineWidget({ locationName, deadlines, nextDeadline }: DeadlineWidgetProps) {
  const [queueStatus, setQueueStatus] = useState<'low' | 'medium' | 'high' | null>(null);
  
  if (deadlines.length === 0) return null;

  const handleWhatsAppShare = () => {
    const text = `🗳️ My Election Plan for ${locationName}:\n\n` + 
      deadlines.map(d => `• ${d.type}: ${d.display}`).join('\n') + 
      `\n\nGenerated by Civix Assistant`;
    
    const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className={cn(
        "rounded-2xl p-5 mb-6 glass relative overflow-hidden",
        nextDeadline?.urgency === 'critical' ? "ring-2 ring-red-500/50" : "ring-1 ring-slate-200"
      )}
    >
      {nextDeadline?.urgency === 'critical' && (
        <div className="absolute top-0 right-0 p-2">
          <AlertCircle className="w-5 h-5 text-red-500 animate-pulse" />
        </div>
      )}

      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center space-x-2">
          <Calendar className="w-5 h-5 text-primary-600" />
          <h3 className="font-bold text-slate-800 text-sm">Deadlines</h3>
        </div>
        <div className="flex space-x-1">
          {locationName?.toLowerCase().includes('india') || true && (
            <a 
              href="https://voters.eci.gov.in/"
              target="_blank"
              rel="noopener noreferrer"
              className="p-2 bg-primary-50 text-primary-600 rounded-lg hover:bg-primary-100 transition-colors"
              title="Official ECI Portal"
            >
              <Info className="w-4 h-4" />
            </a>
          )}
          <button 
            onClick={handleWhatsAppShare}
            className="p-2 bg-green-50 text-green-600 rounded-lg hover:bg-green-100 transition-colors"
            title="Share to WhatsApp"
          >
            <Share2 className="w-4 h-4" />
          </button>
        </div>
      </div>

      <div className="space-y-3 mb-6">
        {deadlines.map((deadline, index) => (
          <div key={index} className="flex items-center justify-between text-sm">
            <span className="text-slate-600 flex items-center">
              <Clock className="w-4 h-4 mr-2 text-slate-400" />
              {deadline.type}
            </span>
            <span className={cn(
              "font-semibold px-2 py-0.5 rounded-full text-[10px] uppercase tracking-wider",
              deadline.urgency === 'critical' && "bg-red-100 text-red-700",
              deadline.urgency === 'soon' && "bg-orange-100 text-orange-700",
              deadline.urgency === 'comfortable' && "bg-green-100 text-green-700",
              deadline.urgency === 'passed' && "bg-slate-100 text-slate-500"
            )}>
              {deadline.display}
            </span>
          </div>
        ))}
      </div>

      <div className="pt-4 border-t border-slate-100">
        <div className="flex items-center justify-between mb-3">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Live Booth Status</span>
          {queueStatus && (
            <span className={cn(
              "text-[9px] font-bold px-2 py-0.5 rounded-full uppercase",
              queueStatus === 'low' && "bg-green-100 text-green-600",
              queueStatus === 'medium' && "bg-orange-100 text-orange-600",
              queueStatus === 'high' && "bg-red-100 text-red-600"
            )}>
              {queueStatus} Queue
            </span>
          )}
        </div>
        <div className="flex gap-2">
          {(['low', 'medium', 'high'] as const).map((status) => (
            <button
              key={status}
              onClick={() => setQueueStatus(status)}
              className={cn(
                "flex-1 py-2 rounded-xl text-[10px] font-bold transition-all border",
                queueStatus === status 
                  ? "bg-slate-900 border-slate-900 text-white shadow-md" 
                  : "bg-white border-slate-200 text-slate-400 hover:border-primary-200"
              )}
            >
              {status === 'low' ? '😊 Clear' : status === 'medium' ? '😐 Busy' : '😫 Crowded'}
            </button>
          ))}
        </div>
        <p className="text-[9px] text-slate-400 mt-3 text-center italic">
          Real-time updates from voters at your booth.
        </p>
      </div>
    </motion.div>
  );
});

export default DeadlineWidget;
